export const queryKeys = {
  me: ["auth", "me"],
  creators: (params) => ["creators", params],
  creator: (id) => ["creator", id],
  creatorProfileMe: ["creators", "profile", "me"],
  savedCreators: ["creators", "saved"],
  requirements: (params) => ["requirements", params],
  requirement: (id) => ["requirement", id],
  myRequirements: ["requirements", "my"],
  quotations: (id) => ["requirements", id, "quotations"],
  myQuotations: ["quotations", "my"],
  orders: ["orders"],
  order: (id) => ["order", id],
  orderFiles: (id) => ["order", id, "files"],
  messages: (id) => ["messages", id],
  payments: ["payments", "history"],
  reviews: (id) => ["reviews", "creator", id],
  notifications: ["notifications"],
  contactSubmissions: ["contact", "admin"],
  adminStats: ["admin", "stats"],
  adminUsers: ["admin", "users"],
  adminRequirements: ["admin", "requirements"],
  adminQuotations: ["admin", "quotations"],
  adminPayouts: ["admin", "payouts"],
  adminPayout: (id) => ["admin", "payout", id],
  adminOrderPayout: (orderId) => ["admin", "order", "payout", orderId],
};
